import { Area } from './types';

export const AREAS: Area[] = [
  {
    id: 'delray-beach',
    name: 'Delray Beach',
    slug: 'delray-beach',
    description: 'Walkable Atlantic Ave, beaches, lively dining.',
    imageSrc: '/neighborhoods/delray-beach-east-delray.jpg',
    featured: true,
    targetSegments: ['55-plus-cash-buyer', 'second-home-buyer', 'professional'],
    developments: ['atlantic-gardens', 'delray-beach-club'],
    articles: ['delray-beach-guide', 'atlantic-ave-dining'],
  },
  {
    id: 'boca-raton',
    name: 'Boca Raton',
    slug: 'boca-raton',
    description: 'Schools, clubs, gated communities, coastal living.',
    imageSrc: '/neighborhoods/boca-raton-mizner.jpg.webp',
    featured: true,
    targetSegments: ['family', 'professional', 'upgrade-downgrade'],
    developments: ['boca-west', 'royal-palm-yacht-club'],
    articles: ['boca-raton-schools', 'mizner-park-guide'],
  },
  {
    id: 'boynton-beach',
    name: 'Boynton Beach',
    slug: 'boynton-beach',
    description: 'Great value, newer builds, easy access.',
    imageSrc: '/neighborhoods/boynton-beach-inet.jpg',
    featured: true,
    targetSegments: ['investor', 'family', 'professional'],
    developments: ['boynton-beach-club', 'ocean-ridge'],
    articles: ['boynton-beach-value', 'investment-opportunities'],
  },
  {
    id: 'wellington',
    name: 'Wellington',
    slug: 'wellington',
    description: 'Equestrian community, family-friendly, excellent schools.',
    imageSrc: '/neighborhoods/wellington-equestrian.jpg',
    featured: true,
    targetSegments: ['family', '55-plus-cash-buyer', 'relocating'],
    developments: ['wellington-national', 'palm-beach-polo'],
    articles: ['wellington-equestrian', 'family-communities'],
  },
  {
    id: 'west-palm-beach',
    name: 'West Palm Beach',
    slug: 'west-palm-beach',
    description: 'Urban living, cultural district, waterfront properties.',
    imageSrc: '/neighborhoods/west-palm-beach-downtown.jpg',
    featured: true,
    targetSegments: ['professional', 'second-home-buyer', 'investor'],
    developments: ['cityplace-tower', 'waterfront-condos'],
    articles: ['west-palm-beach-urban', 'downtown-living'],
  },
];