import { Article } from './types';

export const ARTICLES: Article[] = [
  // 55+ Cash Buyer Content
  {
    id: 'delray-beach-guide',
    title: 'Delray Beach: The Perfect Retirement Destination',
    slug: 'delray-beach-guide',
    excerpt: 'Discover why Delray Beach is the ideal choice for active adults seeking a vibrant retirement lifestyle.',
    content: 'Full article content about Delray Beach retirement living...',
    author: 'Rachel Kovalsky',
    publishDate: '2024-01-15',
    imageSrc: '/articles/delray-beach-retirement.jpg',
    featured: true,
    areas: ['delray-beach'],
    developments: ['atlantic-gardens', 'delray-beach-club'],
    targetSegments: ['55-plus-cash-buyer'],
    tags: ['retirement', 'active-adult', 'delray-beach'],
  },
  {
    id: 'wellington-equestrian',
    title: 'Wellington: Equestrian Paradise for Active Adults',
    slug: 'wellington-equestrian',
    excerpt: 'Explore Wellington\'s world-class equestrian facilities and luxury communities.',
    content: 'Full article content about Wellington equestrian living...',
    author: 'Rachel Kovalsky',
    publishDate: '2024-01-20',
    imageSrc: '/articles/wellington-equestrian.jpg',
    featured: true,
    areas: ['wellington'],
    developments: ['wellington-national', 'palm-beach-polo'],
    targetSegments: ['55-plus-cash-buyer'],
    tags: ['equestrian', 'luxury', 'wellington'],
  },

  // Second Home Buyer Content
  {
    id: 'atlantic-ave-dining',
    title: 'Atlantic Avenue: A Foodie\'s Paradise',
    slug: 'atlantic-ave-dining',
    excerpt: 'The best restaurants and dining experiences along Delray Beach\'s famous Atlantic Avenue.',
    content: 'Full article content about Atlantic Avenue dining...',
    author: 'Rachel Kovalsky',
    publishDate: '2024-01-25',
    imageSrc: '/articles/atlantic-ave-dining.jpg',
    featured: true,
    areas: ['delray-beach'],
    developments: ['atlantic-gardens'],
    targetSegments: ['second-home-buyer'],
    tags: ['dining', 'lifestyle', 'delray-beach'],
  },
  {
    id: 'west-palm-beach-urban',
    title: 'West Palm Beach: Urban Living by the Water',
    slug: 'west-palm-beach-urban',
    excerpt: 'Experience the best of urban living with waterfront access in West Palm Beach.',
    content: 'Full article content about West Palm Beach urban living...',
    author: 'Rachel Kovalsky',
    publishDate: '2024-02-01',
    imageSrc: '/articles/west-palm-urban.jpg',
    featured: true,
    areas: ['west-palm-beach'],
    developments: ['cityplace-tower', 'waterfront-condos'],
    targetSegments: ['second-home-buyer', 'professional'],
    tags: ['urban', 'waterfront', 'west-palm-beach'],
  },

  // Family Content
  {
    id: 'boca-raton-schools',
    title: 'Boca Raton Schools: Excellence in Education',
    slug: 'boca-raton-schools',
    excerpt: 'Why Boca Raton\'s school system makes it the perfect place for families.',
    content: 'Full article content about Boca Raton schools...',
    author: 'Rachel Kovalsky',
    publishDate: '2024-02-05',
    imageSrc: '/articles/boca-schools.jpg',
    featured: true,
    areas: ['boca-raton'],
    developments: ['boca-west', 'royal-palm-yacht-club'],
    targetSegments: ['family'],
    tags: ['schools', 'family', 'boca-raton'],
  },
  {
    id: 'family-communities',
    title: 'Best Family Communities in South Florida',
    slug: 'family-communities',
    excerpt: 'Discover the top family-friendly communities with excellent amenities and schools.',
    content: 'Full article content about family communities...',
    author: 'Rachel Kovalsky',
    publishDate: '2024-02-10',
    imageSrc: '/articles/family-communities.jpg',
    featured: true,
    areas: ['wellington', 'boca-raton'],
    developments: ['wellington-national', 'palm-beach-polo', 'boca-west'],
    targetSegments: ['family'],
    tags: ['family', 'communities', 'amenities'],
  },

  // Professional Content
  {
    id: 'mizner-park-guide',
    title: 'Mizner Park: Boca Raton\'s Premier Lifestyle Destination',
    slug: 'mizner-park-guide',
    excerpt: 'Everything you need to know about living near Mizner Park in Boca Raton.',
    content: 'Full article content about Mizner Park...',
    author: 'Rachel Kovalsky',
    publishDate: '2024-02-15',
    imageSrc: '/articles/mizner-park.jpg',
    featured: true,
    areas: ['boca-raton'],
    developments: ['boca-west'],
    targetSegments: ['professional'],
    tags: ['lifestyle', 'boca-raton', 'mizner-park'],
  },
  {
    id: 'downtown-living',
    title: 'Downtown Living: West Palm Beach\'s Urban Renaissance',
    slug: 'downtown-living',
    excerpt: 'Experience the revitalized downtown West Palm Beach with luxury condos and amenities.',
    content: 'Full article content about downtown West Palm Beach...',
    author: 'Rachel Kovalsky',
    publishDate: '2024-02-20',
    imageSrc: '/articles/downtown-wpb.jpg',
    featured: true,
    areas: ['west-palm-beach'],
    developments: ['cityplace-tower'],
    targetSegments: ['professional', 'second-home-buyer'],
    tags: ['downtown', 'urban', 'west-palm-beach'],
  },

  // Investor Content
  {
    id: 'boynton-beach-value',
    title: 'Boynton Beach: Hidden Gem for Real Estate Investors',
    slug: 'boynton-beach-value',
    excerpt: 'Why Boynton Beach offers the best value and growth potential for investors.',
    content: 'Full article content about Boynton Beach investment opportunities...',
    author: 'Rachel Kovalsky',
    publishDate: '2024-02-25',
    imageSrc: '/articles/boynton-investment.jpg',
    featured: true,
    areas: ['boynton-beach'],
    developments: ['boynton-beach-club', 'ocean-ridge'],
    targetSegments: ['investor'],
    tags: ['investment', 'value', 'boynton-beach'],
  },
  {
    id: 'investment-opportunities',
    title: 'South Florida Real Estate Investment Opportunities',
    slug: 'investment-opportunities',
    excerpt: 'The best areas and property types for real estate investment in South Florida.',
    content: 'Full article content about investment opportunities...',
    author: 'Rachel Kovalsky',
    publishDate: '2024-03-01',
    imageSrc: '/articles/investment-opportunities.jpg',
    featured: true,
    areas: ['boynton-beach', 'delray-beach'],
    developments: ['boynton-beach-club', 'delray-beach-club'],
    targetSegments: ['investor'],
    tags: ['investment', 'real-estate', 'opportunities'],
  },

  // Upgrade/Downgrade Content
  {
    id: 'upgrade-downgrade-guide',
    title: 'Upgrading or Downsizing: Finding Your Perfect Home',
    slug: 'upgrade-downgrade-guide',
    excerpt: 'Navigate the process of upgrading or downsizing your home in South Florida.',
    content: 'Full article content about upgrading/downsizing...',
    author: 'Rachel Kovalsky',
    publishDate: '2024-03-05',
    imageSrc: '/articles/upgrade-downgrade.jpg',
    featured: true,
    areas: ['boca-raton', 'delray-beach'],
    developments: ['boca-west', 'atlantic-gardens'],
    targetSegments: ['upgrade-downgrade'],
    tags: ['upgrade', 'downsize', 'home-buying'],
  },
];
