import { Development } from './types';

export const DEVELOPMENTS: Development[] = [
  // Country Clubs with Buy-in
  {
    id: 'atlantic-gardens',
    name: 'Atlantic Gardens',
    slug: 'atlantic-gardens',
    area: 'delray-beach',
    description: 'Luxury country club living with championship golf and resort amenities.',
    imageSrc: '/developments/atlantic-gardens.jpg',
    amenities: ['golf', 'country-club', 'tennis', 'pool', 'spa', 'restaurant'],
    priceRange: { min: 800000, max: 2500000 },
    featured: true,
    targetSegments: ['55-plus-cash-buyer', 'second-home-buyer'],
  },
  {
    id: 'boca-west',
    name: 'Boca West Country Club',
    slug: 'boca-west',
    area: 'boca-raton',
    description: 'Premier country club with multiple golf courses and luxury amenities.',
    imageSrc: '/developments/boca-west.jpg',
    amenities: ['golf', 'country-club', 'tennis', 'pool', 'gym', 'restaurant'],
    priceRange: { min: 1200000, max: 4000000 },
    featured: true,
    targetSegments: ['55-plus-cash-buyer', 'upgrade-downgrade'],
  },
  {
    id: 'royal-palm-yacht-club',
    name: 'Royal Palm Yacht Club',
    slug: 'royal-palm-yacht-club',
    area: 'boca-raton',
    description: 'Exclusive waterfront country club with marina access.',
    imageSrc: '/developments/royal-palm.jpg',
    amenities: ['golf', 'country-club', 'marina', 'tennis', 'pool', 'beach-access'],
    priceRange: { min: 2000000, max: 8000000 },
    featured: true,
    targetSegments: ['55-plus-cash-buyer', 'second-home-buyer'],
  },

  // Golf Communities
  {
    id: 'wellington-national',
    name: 'Wellington National',
    slug: 'wellington-national',
    area: 'wellington',
    description: 'Golf course community with equestrian facilities.',
    imageSrc: '/developments/wellington-national.jpg',
    amenities: ['golf', 'tennis', 'pool', 'walking-trails'],
    priceRange: { min: 600000, max: 1500000 },
    featured: true,
    targetSegments: ['family', '55-plus-cash-buyer'],
  },
  {
    id: 'palm-beach-polo',
    name: 'Palm Beach Polo',
    slug: 'palm-beach-polo',
    area: 'wellington',
    description: 'Equestrian and golf community with luxury homes.',
    imageSrc: '/developments/palm-beach-polo.jpg',
    amenities: ['golf', 'tennis', 'pool', 'walking-trails', 'dog-park'],
    priceRange: { min: 800000, max: 2000000 },
    featured: true,
    targetSegments: ['family', '55-plus-cash-buyer'],
  },

  // Active Adult Communities
  {
    id: 'delray-beach-club',
    name: 'Delray Beach Club',
    slug: 'delray-beach-club',
    area: 'delray-beach',
    description: 'Active adult community with resort-style amenities.',
    imageSrc: '/developments/delray-beach-club.jpg',
    amenities: ['pickleball', 'tennis', 'pool', 'gym', 'social-club'],
    priceRange: { min: 400000, max: 800000 },
    featured: true,
    targetSegments: ['55-plus-cash-buyer', 'relocating'],
  },
  {
    id: 'boynton-beach-club',
    name: 'Boynton Beach Club',
    slug: 'boynton-beach-club',
    area: 'boynton-beach',
    description: 'Value-focused active adult community with modern amenities.',
    imageSrc: '/developments/boynton-beach-club.jpg',
    amenities: ['pickleball', 'tennis', 'pool', 'fitness-center', 'social-club'],
    priceRange: { min: 300000, max: 600000 },
    featured: true,
    targetSegments: ['55-plus-cash-buyer', 'investor'],
  },

  // Urban/Waterfront
  {
    id: 'cityplace-tower',
    name: 'CityPlace Tower',
    slug: 'cityplace-tower',
    area: 'west-palm-beach',
    description: 'Luxury high-rise living in the heart of downtown.',
    imageSrc: '/developments/cityplace-tower.jpg',
    amenities: ['gym', 'pool', 'restaurant', 'social-club'],
    priceRange: { min: 500000, max: 1200000 },
    featured: true,
    targetSegments: ['professional', 'second-home-buyer'],
  },
  {
    id: 'waterfront-condos',
    name: 'Waterfront Condos',
    slug: 'waterfront-condos',
    area: 'west-palm-beach',
    description: 'Modern waterfront condominiums with marina access.',
    imageSrc: '/developments/waterfront-condos.jpg',
    amenities: ['marina', 'pool', 'gym', 'beach-access'],
    priceRange: { min: 400000, max: 1000000 },
    featured: true,
    targetSegments: ['professional', 'investor', 'second-home-buyer'],
  },
  {
    id: 'ocean-ridge',
    name: 'Ocean Ridge',
    slug: 'ocean-ridge',
    area: 'boynton-beach',
    description: 'Exclusive beachfront community with private beach access.',
    imageSrc: '/developments/ocean-ridge.jpg',
    amenities: ['beach-access', 'tennis', 'pool', 'walking-trails'],
    priceRange: { min: 800000, max: 3000000 },
    featured: true,
    targetSegments: ['55-plus-cash-buyer', 'second-home-buyer'],
  },
  {
    id: 'wycliffe-golf-country-club',
    name: 'Wycliffe Golf & Country Club',
    slug: 'wycliffe-golf-country-club',
    area: 'lake-worth',
    description: 'Private, gated country club community with championship golf and resort amenities.',
    imageSrc: '/developments/wycliffe-golf-country-club.jpg',
    amenities: ['golf', 'country-club', 'tennis', 'pickleball', 'pool', 'spa', 'restaurant', 'social-club', 'walking-trails'],
    priceRange: { min: 800000, max: 2000000 },
    featured: true,
    targetSegments: ['55-plus-cash-buyer', 'second-home-buyer'],
  },
];
