import { MarketData } from './types';

export const MARKET_DATA: MarketData[] = [
  // Delray Beach Market Data
  {
    id: 'delray-median-price',
    area: 'delray-beach',
    metric: 'Median Sale Price',
    value: 675000,
    format: 'currency',
    period: 'Sep 2025',
    source: 'BeachesMLS / local stats',
    featured: true,
  },
  {
    id: 'delray-inventory',
    area: 'delray-beach',
    metric: 'Months of Inventory',
    value: 3.1,
    format: 'raw',
    period: 'Sep 2025',
    source: 'BeachesMLS / local stats',
    featured: true,
  },
  {
    id: 'delray-yoy-change',
    area: 'delray-beach',
    metric: 'YoY Price Change',
    value: 4,
    format: 'percent',
    period: 'vs Sep 2024',
    source: 'BeachesMLS / local stats',
    featured: true,
  },

  // Boca Raton Market Data
  {
    id: 'boca-median-price',
    area: 'boca-raton',
    metric: 'Median Sale Price',
    value: 850000,
    format: 'currency',
    period: 'Sep 2025',
    source: 'BeachesMLS / local stats',
    featured: true,
  },
  {
    id: 'boca-inventory',
    area: 'boca-raton',
    metric: 'Months of Inventory',
    value: 2.8,
    format: 'raw',
    period: 'Sep 2025',
    source: 'BeachesMLS / local stats',
    featured: true,
  },
  {
    id: 'boca-yoy-change',
    area: 'boca-raton',
    metric: 'YoY Price Change',
    value: 6,
    format: 'percent',
    period: 'vs Sep 2024',
    source: 'BeachesMLS / local stats',
    featured: true,
  },

  // Wellington Market Data
  {
    id: 'wellington-median-price',
    area: 'wellington',
    metric: 'Median Sale Price',
    value: 750000,
    format: 'currency',
    period: 'Sep 2025',
    source: 'BeachesMLS / local stats',
    featured: true,
  },
  {
    id: 'wellington-inventory',
    area: 'wellington',
    metric: 'Months of Inventory',
    value: 4.2,
    format: 'raw',
    period: 'Sep 2025',
    source: 'BeachesMLS / local stats',
    featured: true,
  },
  {
    id: 'wellington-yoy-change',
    area: 'wellington',
    metric: 'YoY Price Change',
    value: 3,
    format: 'percent',
    period: 'vs Sep 2024',
    source: 'BeachesMLS / local stats',
    featured: true,
  },

  // West Palm Beach Market Data
  {
    id: 'wpb-median-price',
    area: 'west-palm-beach',
    metric: 'Median Sale Price',
    value: 550000,
    format: 'currency',
    period: 'Sep 2025',
    source: 'BeachesMLS / local stats',
    featured: true,
  },
  {
    id: 'wpb-inventory',
    area: 'west-palm-beach',
    metric: 'Months of Inventory',
    value: 3.5,
    format: 'raw',
    period: 'Sep 2025',
    source: 'BeachesMLS / local stats',
    featured: true,
  },
  {
    id: 'wpb-yoy-change',
    area: 'west-palm-beach',
    metric: 'YoY Price Change',
    value: 5,
    format: 'percent',
    period: 'vs Sep 2024',
    source: 'BeachesMLS / local stats',
    featured: true,
  },

  // Boynton Beach Market Data
  {
    id: 'boynton-median-price',
    area: 'boynton-beach',
    metric: 'Median Sale Price',
    value: 450000,
    format: 'currency',
    period: 'Sep 2025',
    source: 'BeachesMLS / local stats',
    featured: true,
  },
  {
    id: 'boynton-inventory',
    area: 'boynton-beach',
    metric: 'Months of Inventory',
    value: 3.8,
    format: 'raw',
    period: 'Sep 2025',
    source: 'BeachesMLS / local stats',
    featured: true,
  },
  {
    id: 'boynton-yoy-change',
    area: 'boynton-beach',
    metric: 'YoY Price Change',
    value: 7,
    format: 'percent',
    period: 'vs Sep 2024',
    source: 'BeachesMLS / local stats',
    featured: true,
  },
];
